# Generated by Django 5.1.2 on 2024-11-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_disease', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='CustomerInsuranceInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_insuranceinfo',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_profile',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='ItemInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=45)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'item_insurance',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='status', max_length=45, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='TypeOfInsurance',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='type_of_insurance', max_length=45, null=True)),
            ],
            options={
                'db_table': 'type_of_insurance',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='CustomerHealthInsurance',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_of_the_hospital', models.CharField(blank=True, max_length=45, null=True)),
                ('price_of_health_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.checklist')),
                ('customer_insuranceinfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.customerinsuranceinfo')),
            ],
            options={
                'db_table': 'customer_health_insurance',
            },
        ),
        migrations.AddField(
            model_name='customerinsuranceinfo',
            name='CustomerProfile',
            field=models.ForeignKey(blank=True, db_column='customer_profile_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.customerprofile'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.gender'),
        ),
        migrations.AddField(
            model_name='customerinsuranceinfo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.status'),
        ),
        migrations.AddField(
            model_name='customerinsuranceinfo',
            name='type_of_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.typeofinsurance'),
        ),
        migrations.CreateModel(
            name='CustomerItemInsurance',
            fields=[
                ('customer_insuranceinfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.customerinsuranceinfo')),
                ('price_of_item_insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.iteminsurance')),
            ],
            options={
                'db_table': 'customer_item_insurance',
            },
        ),
        migrations.CreateModel(
            name='WorkerHasCustomerProfile',
            fields=[
                ('worker', models.ForeignKey(db_column='fk_worker_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.worker')),
                ('customer_profile', models.ForeignKey(db_column='fk_customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='company.customerprofile')),
            ],
            options={
                'db_table': 'worker_has_customer_profile',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='Customers',
            field=models.ManyToManyField(through='company.WorkerHasCustomerProfile', to='company.customerprofile'),
        ),
    ]
