# Generated by Django 5.1.2 on 2024-10-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsuranceInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_insuranceinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='status', max_length=45, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfInsurance',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='type_of_insurance', max_length=45, null=True)),
            ],
            options={
                'db_table': 'type_of_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='WorkerHasCustomerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_profile', models.ForeignKey(db_column='customer_profile_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.customerprofile')),
                ('worker', models.ForeignKey(db_column='worker_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.worker')),
            ],
            options={
                'db_table': 'worker_has_customer_profile',
                'unique_together': {('worker', 'customer_profile')},
            },
        ),
    ]
