# Generated by Django 5.1.2 on 2024-10-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_disease', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'checklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerHealthInsurance',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_of_the_hospital', models.CharField(blank=True, max_length=45, null=True)),
                ('price_of_health_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customer_health_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerItemInsurance',
            fields=[
                ('customer_insuranceinfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.customerinsuranceinfo')),
                ('price_of_item_insurance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'customer_item_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=45)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'item_insurance',
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='workerhascustomerprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='worker',
            name='Customers',
            field=models.ManyToManyField(through='company.WorkerHasCustomerProfile', to='company.customerprofile'),
        ),
        migrations.AlterField(
            model_name='workerhascustomerprofile',
            name='customer_profile',
            field=models.ForeignKey(db_column='fk_customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='company.customerprofile'),
        ),
        migrations.AlterField(
            model_name='workerhascustomerprofile',
            name='worker',
            field=models.ForeignKey(db_column='fk_worker_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.worker'),
        ),
        migrations.RemoveField(
            model_name='workerhascustomerprofile',
            name='id',
        ),
    ]
