# Generated by Django 5.1.2 on 2024-12-11 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhealthinsurance',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customeriteminsurance',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
